apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: quotehub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: api
        image: ${QUOTE_API_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_DATABASE
        - name: MARIADB_HOST
          value: "mariadb.quotehub.svc.cluster.local"
        - name: MARIADB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: quote-api
  namespace: quotehub
spec:
  selector:
    app: quote-api
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP 